[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nebkit"
version = "0.1.0"
dependencies = [
    "ase",
    "pymatgen",
    "scipy",
    "rdkit",
    "mp-api"
]

[tool.setuptools.packages.find]
include = ["nebkit*"]
exclude = ["recycle*", "test*", "pics*"]